- .travis.yml
- README.md
- lib/Storage.js
- lib/TvmClient.js
- package-lock.json
- package.json
- test/jest.setup.js
- test/lib/AzureStorage.test.js
Add travis CI + small readme fixes and version bump
**+Windows fixes**
> Make ready for NPM release

- README.md
- index.js
- lib/Storage.js
- lib/TvmClient.js
- lib/azure/AzureStorage.js
- package.json
- test/lib/AzureStorage.test.js
- test/lib/TvmClient.test.js
- bug fixes:
- make sure create container error code is read properly
- fix root listing when using account credentials
- travis badge
- new tvm endpoint
- bump to 0.1.1
unit test + manual tests (no integration tests yet)
> Change TVM endpoint, various fixes and bump to 0.1.1

- lib/TvmClient.js
- package.json
- test/lib/TvmClient.test.js
change request method to tvm to get
> change request method to tvm to get

- doc/api.md
- lib/Files.js
- lib/FilesError.js
- lib/impl/AzureBlobFiles.js
- lib/init.js
- lib/types.jsdoc.js
- package-lock.json
- package.json
- test/Files.test.js
- test/impl/AzureBlobFiles.test.js
- test/init.test.js
- test/jest.setup.js
> ACNA-317 - integrate with core error handling sdk

- README.md
- lib/Files.js
- lib/FilesError.js
- lib/impl/AzureBlobFiles.js
- lib/init.js
- lib/utils.js
- package.json
- test/Files.test.js
- test/impl/AzureBlobFiles.test.js
- test/init.test.js
- test/jest.setup.js
> ACNA-436 - Integrate logging sdk

- lib/Files.js
- lib/FilesError.js
- lib/impl/AzureBlobFiles.js
- test/impl/AzureBlobFiles.test.js
- test/jest.setup.js
- remove error log when 404 on _fileExists
- make sure to properly stringify all errors
> fix error logs

- lib/FilesError.js
- lib/init.js
- test/init.test.js
fix error handling, was not getting status correctly
> fix tvm error handling

- .gitignore
- e2e/e2e.js
- e2e/e2e.md
- jest.e2e.config.js
- lib/Files.js
- lib/FilesError.js
- lib/impl/AzureBlobFiles.js
- package.json
- test/Files.test.js
- test/impl/AzureBlobFiles.test.js
- test/jest.setup.js
- e2e tests
- e2e tests doc (todo)
- fixes:
- fixed private files starting with 'public<myfile>' that where considered public
- fixed bad length/position for read options
- copy files remote to remote was broken
> ACNA-455 - e2e tests and various fixes

- lib/Files.js
- lib/FilesError.js
- lib/impl/AzureBlobFiles.js
- lib/init.js
fix logger lib breaking change
> fix logger update breaking change

- README.md
- doc/api.md
- e2e/e2e.js
- lib/init.js
- package.json
update to latest aio lib core tvm
> fix reading OW env var

- package.json
- test/Files.test.js
- test/impl/AzureBlobFiles.test.js
- test/init.test.js
- test/jest.setup.js
> chore(package): update eslint-plugin-jest to version 23.1.1

- index.js
> ACNA-561 - Fixing autocompletion

- doc/api.md
- jsconfig.json
- lib/Files.js
- lib/FilesError.js
- lib/impl/AzureBlobFiles.js
- lib/init.js
- lib/types.jsdoc.js
- package.json
- types.d.ts
Trying to improve autocomplete in VS Code.
Better developer experience.
1. npm test
2. vs code autocomplete
> fix: generate typings from jsdoc

- doc/api.md
- lib/Files.js
- package.json
- types.d.ts
> fix autocompletion and protected methods

- README.md
- doc/api.md
- lib/Files.js
- lib/FilesError.js
- lib/impl/AzureBlobFiles.js
- lib/init.js
- lib/utils.js
- package.json
- test/Files.test.js
- test/impl/AzureBlobFiles.test.js
- test/init.test.js
Added support to share private files using presign URLs
All file URLs will now be routed via CDN so made changes to getURL to return appropriate URLs
unit test, manual tests
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
> Presign URL support

- lib/Files.js
- lib/FilesError.js
- package.json
- test/impl/AzureBlobFiles.test.js
- test/init.test.js
- test/jest.setup.js
Make it obvious that BAD_CREDENTIALS could be a FW issue
Relates to https://github.com/adobe/aio-lib-state/pull/54
> Add firewall error message to 403

- README.md
Update README to include description and link to Pojrect Firefly
N/A
Clarify usage of the library
Doc change, no test needed
> update README to include Firefly info

- .github/workflows/on-push-publish-to-npm.yml
- .github/workflows/version-bump-publish.yml
Changes to use GH actions for NPM release.
> Add GH action workflow files for NPM release.

- package.json
> Bump versions of dependencies

- .github/workflows/node.js.yml
- .github/workflows/on-push-publish-to-npm.yml
- .github/workflows/version-bump-publish.yml
- lib/Files.js
- lib/impl/AzureBlobFiles.js
- lib/init.js
- lib/types.jsdoc.js
- package.json
Fixes `daily.yml` Github Action failure under node-16.
1. nvm use 16
2. rm -rf node_modules
3. rm package-lock.json
4. npm i --package-lock --package-lock-only
5. npm test
> update @adobe/eslint-config-aio-lib-config and its peer dependencies. fix for node-16

- .github/dependabot.yml
- package.json
Adding dependabot to the repo.
[ACNA-1969](https://jira.corp.adobe.com/browse/ACNA-1969)
> ACNA-1969 | dependabot added

- lib/impl/AzureBlobFiles.js
- package.json
- test/Files.test.js
- test/__mocks__/FileError.js
- test/jest.setup.js
> chore(dev-deps): update jest to ^29

- lib/impl/AzureBlobFiles.js
- test/impl/AzureBlobFiles.test.js
> limit file list results to 1000 items

- lib/Files.js
- lib/impl/AzureBlobFiles.js
- test/impl/AzureBlobFiles.test.js
> fix: container public presign

- README.md
- doc/api.md
- lib/Files.js
- types.d.ts
will require a release for typings
> chore: doc change for list
